# Generated by Django 5.0.4 on 2024-04-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_rename_portifolio_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='linguagem',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('DJANGO', 'Django'), ('HTML', 'HTML'), ('CSS', 'CSS')], default='', max_length=100),
        ),
    ]
