# Generated by Django 5.0.4 on 2024-04-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_projeto_linguagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='genero',
        ),
    ]
