# Generated by Django 5.0.4 on 2024-04-23 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_remove_projeto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_postagem',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
