# Generated by Django 5.0.4 on 2024-04-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0008_alter_projeto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
