# Generated by Django 5.0.4 on 2024-04-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0010_projeto_texto_objetivo_projeto_texto_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
