# Generated by Django 5.0.4 on 2024-05-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0011_projeto_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
    ]
